apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
  namespace: orchestrator
data:
  NODE_ENV: "production"
  MONGO_URI: "mongodb://mongo:27017/containersDB"
  DOCKER_HOST: "unix:///var/run/docker.sock"
  INSTANCE_ID: "k8s-backend" 