apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-orchestrator
  namespace: monitoring
  labels:
    app: backend-orchestrator
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend-orchestrator
  namespaceSelector:
    matchNames:
    - orchestrator
    - default
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-orchestrator
  namespace: monitoring
  labels:
    app: frontend-orchestrator
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: frontend-orchestrator
  namespaceSelector:
    matchNames:
    - orchestrator
    - default
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http



