apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-github-config
  namespace: sonarqube
data:
  sonar.properties: |
    # GitHub Integration Configuration
    sonar.auth.github.enabled=true
    sonar.auth.github.clientId.secured=Iv23lieBjjZILZJvMTBv
    sonar.auth.github.clientSecret.secured=cf095467ca4081a78fb9350b01b243e6c5c47bfb
    # Optional: uncomment and set your GitHub organization
    # sonar.auth.github.organizations=your-org-name
    
    # GitHub App Configuration
    sonar.auth.github.appId=2061816
    sonar.auth.github.privateKeyPath=/opt/sonarqube/conf/github-private-key.pem
    
    # Authentication Settings
    sonar.auth.github.allowUsersToSignUp=true
    sonar.auth.github.syncUserGroups=true
    
    # Webhook Configuration
    sonar.webhooks.github.enabled=true
  
