name: Local Registry CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: localhost:6500
  FRONTEND_IMAGE: orchestrator-frontend
  BACKEND_IMAGE: orchestrator-backend
  NAMESPACE: orchestrator

jobs:
  # Lint and Test Backend
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend_orchestrator/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend_orchestrator
        run: npm ci

      - name: Run backend linting
        working-directory: ./backend_orchestrator
        run: npm run lint || echo "Linting not configured"

      - name: Run backend tests
        working-directory: ./backend_orchestrator
        run: npm test || echo "Tests not configured"

  # Lint and Test Frontend
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend_orchestrator/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend_orchestrator
        run: npm ci

      - name: Run frontend linting
        working-directory: ./frontend_orchestrator
        run: npm run lint || echo "Linting not configured"

      - name: Run frontend tests
        working-directory: ./frontend_orchestrator
        run: npm test || echo "Tests not configured"

  # Build Images for Local Registry
  build-images:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend_orchestrator
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend_orchestrator
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save images as artifacts
        run: |
          docker save ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest -o backend-image.tar
          docker save ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest -o frontend-image.tar

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            backend-image.tar
            frontend-image.tar
          retention-days: 1

  # Deploy to Kubernetes (Manual trigger)
  deploy:
    needs: build-images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          # Apply Kubernetes manifests
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secrets.yaml
          
          # Update deployment images to use local registry
          kubectl set image deployment/frontend-orchestrator frontend=${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest -n $NAMESPACE
          kubectl set image statefulset/backend-orchestrator backend=${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest -n $NAMESPACE
          
          # Wait for rollout
          kubectl rollout status deployment/frontend-orchestrator -n $NAMESPACE
          kubectl rollout status statefulset/backend-orchestrator -n $NAMESPACE

      - name: Health check
        run: |
          # Wait for services to be ready
          kubectl wait --for=condition=ready pod -l app=frontend-orchestrator -n $NAMESPACE --timeout=300s
          kubectl wait --for=condition=ready pod -l app=backend-orchestrator -n $NAMESPACE --timeout=300s
          
          # Basic health check
          kubectl get pods -n $NAMESPACE
          kubectl get services -n $NAMESPACE

  # Security Scan
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif' 